### ISSUE TITLE
install typography plugin

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-native-shoppin-list#5]
https://github.com/hectahertz/react-native-typography

**Comment by vineeshvk** [comment]
I have just installed the plugin, Because there were three main choices for text style. So if you want to use this please select a style to continue with.

**Comment by atherdon** [comment]
second looks cool


On 03-Jul-2018 at 04:11 PM, Vineesh VK wrote:


I have just installed the plugin, Because there were three main choices for
text style. So if you want to use this please select a style to continue
with.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-native-shoppin-list/issues/5#issuecomment-402211291>,
or mute the thread
