### ISSUE TITLE
deploy app to expo

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-native-shoppin-list#6]
https://expo.io/

**Comment by vineeshvk** [comment]
Oh. I you want me to do it that I need to create the project from scratch because I used react-native-cli rather than create-react-native-app. l'll soon update the repo.

**Comment by atherdon** [comment]
perfect!


On 04-Jul-2018 at 01:33 AM, Vineesh VK wrote:


Oh. I you want me to do it that I need to create the project from scratch
because I used react-native-cli rather than create-react-native-app. l'll
soon update the repo.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-native-shoppin-list/issues/6#issuecomment-402337025>,
or mute the thread

**Comment by vineeshvk** [comment]
I finished the converting the project to expo compatible. Now should I deploy under my name in expo or Is there an account for GroceriStar.

**Comment by atherdon** [comment]
please publish it on your name for this moment. and please add to readme
file link to expo preview page


On 04-Jul-2018 at 03:54 PM, Vineesh VK wrote:


I finished the converting the project to expo compatible. Now should I
deploy under my name in expo or Is there an account for GroceriStar.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-native-shoppin-list/issues/6#issuecomment-402515598>,
or mute the thread

**Comment by vineeshvk** [comment]
Okay sure.

**Comment by atherdon** [comment]
and tell me when it'll be done so we can close this task too

**Comment by vineeshvk** [comment]
Okay done.

**Comment by atherdon** [comment]
Btw, can you add some screenshots?

**Comment by atherdon** [comment]
not necessary, but it'll be cool

**Comment by vineeshvk** [comment]
Okay sure.
